<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
	 /**
     * Return Documents that match a given term
     *
     * @param string $term search term
     *
     * @return Array
     */
	public function search($term) {
		$qb = $this->createQueryBuilder('d');

		return $qb->where("d.title LIKE :term")
				->orWhere("d.content LIKE :term")
				->setParameter('term', '%'.$term.'%')
				->getQuery()
				->getResult();
	}
}
